<?xml version="1.0" encoding="utf-8"?><Database Name="VehicleRental" Class="CarSharingDataBaseClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-RN9AI5Q;Initial Catalog=VehicleRental;Integrated Security=True" SettingsObjectName="CarSharingApplication.Properties.Settings" SettingsPropertyName="VehicleRentalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Categories">
      <Column Name="ID_Category" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DriverLicence" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="DriversLicences_Categories" Member="DriversLicences" ThisKey="ID_DriverLicence" OtherKey="ID_DriverLicence" Type="DriversLicences" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Classes" Member="Classes">
    <Type Name="Classes">
      <Column Name="Class" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Classes_Vehicles" Member="Vehicles" ThisKey="Class" OtherKey="Class" Type="Vehicles" />
    </Type>
  </Table>
  <Table Name="dbo.DriversLicences" Member="DriversLicences">
    <Type Name="DriversLicences">
      <Column Name="ID_DriverLicence" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReceiptDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DriversLicences_Categories" Member="Categories" ThisKey="ID_DriverLicence" OtherKey="ID_DriverLicence" Type="Categories" />
      <Association Name="DriversLicences_Rentals" Member="Rentals" ThisKey="ID_DriverLicence" OtherKey="ID_DriverLicence" Type="Rentals" />
      <Association Name="DriversLicences_TrafficAccidents" Member="TrafficAccidents" ThisKey="ID_DriverLicence" OtherKey="ID_DriverLicence" Type="TrafficAccidents" />
      <Association Name="Rental_Users_DriversLicences" Member="Rental_Users" ThisKey="ID_User" OtherKey="ID_User" Type="Rental_Users" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rental_Admins" Member="Rental_Admins">
    <Type Name="Rental_Admins">
      <Column Name="ID_Admin" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Rental_Users_Rental_Admins" Member="Rental_Users" ThisKey="ID_User" OtherKey="ID_User" Type="Rental_Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rental_Users" Member="Rental_Users">
    <Type Name="Rental_Users">
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserLogin" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="UserEMail" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="UserPassword" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="UserStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserSurname" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="UserMiddleName" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="UserBirthDay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Rental_Users_DriversLicences" Member="DriversLicences" ThisKey="ID_User" OtherKey="ID_User" Type="DriversLicences" />
      <Association Name="Rental_Users_Rental_Admins" Member="Rental_Admins" ThisKey="ID_User" OtherKey="ID_User" Type="Rental_Admins" />
    </Type>
  </Table>
  <Table Name="dbo.Rentals" Member="Rentals">
    <Type Name="Rentals">
      <Column Name="ID_Rental" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DriverLicence" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Vehicle" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="RentalTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="CountOfHours" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="DriversLicences_Rentals" Member="DriversLicences" ThisKey="ID_DriverLicence" OtherKey="ID_DriverLicence" Type="DriversLicences" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Vehicles_Rentals" Member="Vehicles" ThisKey="ID_Vehicle" OtherKey="ID_Vehicle" Type="Vehicles" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrafficAccidents" Member="TrafficAccidents">
    <Type Name="TrafficAccidents">
      <Column Name="ID_TrafficAccident" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Vehicle" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_DriverLicence" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="ID_TrafficAccidentType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Damage" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TrafficAccidentDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="DriversLicences_TrafficAccidents" Member="DriversLicences" ThisKey="ID_DriverLicence" OtherKey="ID_DriverLicence" Type="DriversLicences" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TrafficAccidentTypes_TrafficAccidents" Member="TrafficAccidentTypes" ThisKey="ID_TrafficAccidentType" OtherKey="ID_TrafficAccidentType" Type="TrafficAccidentTypes" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Vehicles_TrafficAccidents" Member="Vehicles" ThisKey="ID_Vehicle" OtherKey="ID_Vehicle" Type="Vehicles" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrafficAccidentTypes" Member="TrafficAccidentTypes">
    <Type Name="TrafficAccidentTypes">
      <Column Name="ID_TrafficAccidentType" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TrafficAccidentTypeName" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Association Name="TrafficAccidentTypes_TrafficAccidents" Member="TrafficAccidents" ThisKey="ID_TrafficAccidentType" OtherKey="ID_TrafficAccidentType" Type="TrafficAccidents" />
    </Type>
  </Table>
  <Table Name="dbo.VehicleCoordinates" Member="VehicleCoordinates">
    <Type Name="VehicleCoordinates">
      <Column Name="ID_Coodinates" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Vehicle" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="StayDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Vehicles_VehicleCoordinates" Member="Vehicles" ThisKey="ID_Vehicle" OtherKey="ID_Vehicle" Type="Vehicles" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VehicleRegistrCertificates" Member="VehicleRegistrCertificates">
    <Type Name="VehicleRegistrCertificates">
      <Column Name="CertificateSeries" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CertificateNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Vehicle" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VIN" Type="System.String" DbType="Char(14) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationNum" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Mark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Vehicle_Type" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Vehicle_Category" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ManufactureYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Chassis" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BodyNo" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="EngineHP_kW" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EcologicalClass" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="PermissibleMaximumWeightKg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WeightWithoutLoadKg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Vehicles_VehicleRegistrCertificates" Member="Vehicles" ThisKey="ID_Vehicle" OtherKey="ID_Vehicle" Type="Vehicles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vehicles" Member="Vehicles">
    <Type Name="Vehicles">
      <Column Name="ID_Vehicle" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PricePerHour" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Class" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="CarPicture" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Vehicles_Rentals" Member="Rentals" ThisKey="ID_Vehicle" OtherKey="ID_Vehicle" Type="Rentals" />
      <Association Name="Vehicles_TrafficAccidents" Member="TrafficAccidents" ThisKey="ID_Vehicle" OtherKey="ID_Vehicle" Type="TrafficAccidents" />
      <Association Name="Vehicles_VehicleCoordinates" Member="VehicleCoordinates" ThisKey="ID_Vehicle" OtherKey="ID_Vehicle" Type="VehicleCoordinates" />
      <Association Name="Vehicles_VehicleRegistrCertificates" Member="VehicleRegistrCertificates" ThisKey="ID_Vehicle" OtherKey="ID_Vehicle" Type="VehicleRegistrCertificates" />
      <Association Name="Classes_Vehicles" Member="Classes" ThisKey="Class" OtherKey="Class" Type="Classes" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>